name:                xmonad-jereksel
version:             0.1.0.0
github:              "jereksel/xmonad-jereksel"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jereksel/xmonad-jereksel#readme>

dependencies:
- base >= 4.7 && < 5
- xmonad-contrib >= 0.13 && < 0.16
- xmonad >= 0.13 && < 0.16
- friday > 0.2 && < 0.3
- directory >= 1.3 && < 1.4
- vector >= 0.12 && < 0.13
- random >= 1.1 && < 1.2
- text >= 0.11 && < 2
- split >= 0.2 && < 0.3
- utf8-string >= 1.0 && < 2.0
- containers >= 0.5 && < 0.7
- mtl >= 2.2 && < 2.3
- X11 >= 1.9 && < 1.10

library:
  source-dirs: src

tests:
  xmonad-contrib-jereksel-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-jereksel
