resolver: lts-12.19

packages:
- .
- location:
    git: https://github.com/xmonad/xmonad-contrib
    commit: v0.14
  extra-dep: true
- location:
    git: https://github.com/xmonad/xmonad
    commit: v0.14
  extra-dep: true
- location:
    git: https://github.com/RaphaelJ/friday-devil.git
    commit: 73181586307a4db93302bfeb9af9ded615e60a07
  extra-dep: true
