resolver: lts-14.1

packages:
- .

extra-deps:
  - xmonad-0.15
  - xmonad-contrib-0.15
  - git: https://github.com/RaphaelJ/friday-devil.git
    commit: 73181586307a4db93302bfeb9af9ded615e60a07
  - text-1.2.4.0
  - friday-0.2.3.1
  - containers-0.5.11.0
  - ratio-int-0.1.2
  - binary-0.8.8.0
